#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

# Match the rust toolchain with that in the rust-sel4 repository for best results.

[toolchain]
channel = "nightly-2023-08-02"
components = [ "rustfmt", "rust-src" ]
